server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ???
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
mybatis:
  ##映射xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    ##映射日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #转换成驼峰

logging:
  level:
    org:
      springframework=DEBUG:
